tap "beeftornado/rmtree"
tap "caskroom/versions"
tap "electric-it/electric-it"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "koekeishiya/formulae"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "romkatv/powerlevel10k"
tap "warrensbox/tap"
brew "ant"
brew "asdf"
brew "avrdude"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bash-completion"
brew "bootloadhid"
brew "clang-format"
brew "go"
brew "dep"
brew "dfu-programmer"
brew "dfu-util"
brew "fish"
brew "git"
brew "gnupg"
brew "jq"
brew "mas"
brew "maven"
brew "neofetch"
brew "pre-commit"
brew "python"
brew "rsync"
brew "starship"
brew "terraform", link: false
brew "terraform-docs"
brew "terragrunt"
brew "tflint"
brew "vim"
brew "yarn"
brew "electric-it/electric-it/cago"
brew "osx-cross/arm/arm-gcc-bin@8", link: true
brew "osx-cross/avr/avr-gcc@8", link: true
brew "qmk/qmk/qmk"
brew "warrensbox/tap/tfswitch"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "apple-events"
cask "bettertouchtool"
cask "box-sync"
cask "cheatsheet"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "flux"
cask "font-fira-code"
cask "font-firacode-nerd-font"
cask "font-hack"
cask "font-hack-nerd-font"
cask "font-inconsolata-g"
cask "font-inconsolata-g-for-powerline"
cask "gimp"
cask "imageoptim"
cask "iterm2"
cask "java"
cask "keyboard-maestro"
cask "logitech-options"
cask "parallels"
cask "postman"
cask "slack"
cask "tableau"
cask "the-unarchiver"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "Helium", id: 1294059664
mas "iMovie", id: 408981434
mas "Microsoft Remote Desktop", id: 1295203466
mas "Things3", id: 904280696
