#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings


# Window settings
yabai -m config layout                       bsp
yabai -m config window_topmost               off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config split_type                   auto
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15

yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config normal_window_opacity        0.90
yabai -m config active_window_opacity        1.0
yabai -m config window_opacity_duration      0.0
yabai -m config window_animation_duration    0.0

# Border settings
yabai -m config window_border                on
yabai -m config window_border_hidpi          off
yabai -m config window_border_blur           off
yabai -m config window_border_width          4
yabai -m config window_border_radius         10
yabai -m config normal_window_border_color   0x002d2a2e
yabai -m config active_window_border_color   0xfffcfcfa
yabai -m config insert_feedback_color        0xffd75f5f

# Mouse settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# Unmanaged applications
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^Arc$" title="^(Account|General|Shortcuts|Little Arc|Previews|Updates|Archive|Site Settings|Advanced)$" manage=off
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off sticky=on
yabai -m rule --add app="^ImageOptim$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off sticky=on
yabai -m rule --add app="^The Unarchiver$" manage=off

# Run scripts on given events
# yabai -m signal --add event=window_created action="~/.config/yabai/three-columns.sh"
# yabai -m signal --add event=window_destroyed action="~/.config/yabai/three-columns.sh"
# yabai -m signal --add event=space_changed action="~/.config/yabai/three-columns.sh"

# yabai -m rule --add app="Slack" space=3

echo "yabai -- config loaded"
