return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "biome",
      "clangd",
      "css-lsp",
      "eslint-lsp",
      "gopls",
      "html-lsp",
      "json-lsp",
      "lemminx",
      "lua-language-server",
      "marksman",
      "prettier",
      "pylyzer",
      "shfmt",
      "sqlfluff",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "taplo",
      "vim-language-server",
      "vtsls",
      "yaml-language-server",
    },
  },
}
