return {}
-- return {
--   "olimorris/onedarkpro.nvim",
--   priority = 1000, -- Ensure it loads first
--   opts = {
--     colors = {
--       bg = "#2d2a2e",
--       fg = "#fcfcfa",
--       red = "#ff6188",
--       orange = "#fc9867",
--       yellow = "#ffd866",
--       green = "#a9dc76",
--       cyan = "#ab9df2",
--       blue = "#78dce8",
--       purple = "#ab9df2",
--       white = "#fcfcfa",
--       black = "#727072",
--       gray = "#5c6370",
--       highlight = "#424144",
--       comment = "#706e70",
--       none = "NONE",
--     },
--   },
-- }
